# fly.toml – mws
app            = "mws"
primary_region = "fra"

[build]

[http_service]
internal_port        = 3000
force_https          = true
auto_stop_machines   = "off"   # never stop the VM
auto_start_machines  = false   # no need to cold-start
min_machines_running = 1       # keep one machine warm
processes            = ["app"]

[[vm]]
memory    = "1gb"
cpu_kind  = "shared"
cpus      = 1
